# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [3]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [4]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.86423574 0.10685692 0.94853276 ... 0.4275529  0.78829847 0.1857762 ]
 [0.68574993 0.11873044 0.51419974 ... 0.50779416 0.3352573  0.12578031]
 [0.49514954 0.50818266 0.73345053 ... 0.86049024 0.69051989 0.18327305]
 ...
 [0.78163326 0.20620459 0.88820022 ... 0.36180625 0.61801743 0.24877863]
 [0.19338468 0.09147166 0.26567351 ... 0.21613057 0.07956426 0.46651631]
 [0.93443346 0.49195017 0.73961972 ... 0.14619799 0.17535449 0.10040723]]
[[0.25225562 0.29270099 0.69517099 ... 0.32880188 0.55498908 0.65995959]
 [0.10069913 0.35966398 0.47916536 ... 0.33301605 0.28366484 0.04095102]
 [0.58664258 0.36335941 0.40168431 ... 0.82080474 0.00179926 0.05797161]
 ...
 [0.2218124  0.34332013 0.3670735  ... 0.25866424 0.02456801 0.34720147]
 [0.74418508 0.89101915 0.86146195 ... 0.99689043 0.63981088 0.11511609]
 [0.34519825 0.91341397 0.15588499 ... 0.58043661 0.98078553 0.70081045]]


Без использования numpy

In [5]:
def mult(a, b):
    result = [[0] * len(a) for _ in range(len(a))]

    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]

    return result


C использованием numpy

In [6]:
def np_mult(a, b):
    return np.dot(a, b)

In [7]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 717 ms, sys: 291 µs, total: 717 ms
Wall time: 722 ms


In [8]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 565 µs, sys: 932 µs, total: 1.5 ms
Wall time: 4.42 ms


In [9]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5266010677805752e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [10]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.73978952 0.79612719 0.87844201] [0.93350413 0.88559727 0.41780119]


In [11]:
def scalar_product(a,b):
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [12]:
def np_scalar_product(a,b):
    return a.dot(b)

In [13]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 0 ns, sys: 67 µs, total: 67 µs
Wall time: 37 µs
CPU times: user 2.16 ms, sys: 25 µs, total: 2.18 ms
Wall time: 2.22 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:**NumPy обеспечивает высокую производительность благодаря оптимизированным алгоритмам, векторизации операций, эффективному управлению памятью и интеграции с другими библиотеками для научных вычислений.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [14]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag = np.diagonal(a)
  res = diag[diag % 2 == 0].sum()
  return res

In [15]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[6, 6, 6, 9, 2],
       [6, 8, 4, 9, 3],
       [5, 8, 7, 4, 2],
       [1, 8, 8, 3, 7],
       [4, 5, 8, 7, 7]])

In [16]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 124 µs, sys: 0 ns, total: 124 µs
Wall time: 128 µs


14

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [17]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = np.zeros_like(A)
    for i in range(len(A)):
        result[i, :] = np.cumsum(A[i])
    return result

In [18]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.31696668 0.81147681 0.7853537  0.19137419 0.96607807 0.9338087
 0.9775545  0.48629537 0.24721896 0.1677014  0.46254535 0.85229348
 0.57311698 0.92725706 0.41899224 0.01043558 0.57436172 0.65444395
 0.80895544 0.19721623 0.06132271 0.97214563 0.09499295 0.95258488
 0.86578305 0.83187396 0.91111581 0.36060622 0.52501489 0.77583845
 0.67999926 0.8225395  0.64003347 0.35126368 0.44555627 0.79789088
 0.95325173 0.09866894 0.32533904 0.84625287 0.82202531 0.91957878
 0.94580027 0.74639205 0.54125157 0.62962911 0.05577673 0.55331588
 0.4746342  0.27418617 0.67358729 0.38260226 0.6191174  0.3493523
 0.28269951 0.48387476 0.45320139 0.0086271  0.13010495 0.68051446
 0.95763645 0.23353299 0.39670484 0.10647386 0.04159241 0.90527557
 0.48697247 0.97156836 0.83286167 0.66176444 0.77656164 0.64719203
 0.70924734 0.58436253 0.50518423 0.67732097 0.80102474 0.11959322
 0.75956787 0.81939431 0.13049921 0.68442777 0.34637785 0.82476337
 0.6267441  0.97120265 0.09326289 0.8020435  0.85755144 0.386284

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [19]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    ia = np.asarray(a)
    n = len(ia)
    if n == 0:
        return (None, None)
    else:
        y = np.array(ia[1:] != ia[:-1])
        i = np.append(np.where(y), n - 1)
        z = np.diff(np.append(-1, i))
        return(ia[i], z)

In [20]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 255 µs, sys: 0 ns, total: 255 µs
Wall time: 226 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [23]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()

    transformed_X[1::2] = a

    transformed_X[::2] **= 3

    reversed_transformed_X = transformed_X[::-1]

    return np.concatenate((X, reversed_transformed_X))

In [24]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 0 ns, sys: 225 µs, total: 225 µs
Wall time: 645 µs
